# Site settings
author: Jahde Cook
title: A Writer's Look on Coding
header-img: img/home-bg.png
email: jahdeofelia@gmail.com
copyright_name: Jahde Cook
description: > # this means to ignore newlines until "baseurl:"
  How a creatively inclined writer goes about the code learning process
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jahde17

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
